ALTER TABLE Flight ADD airline_id INT NULL;
ALTER TABLE Flight ADD gate_id INT NULL;
ALTER TABLE Flight ADD CONSTRAINT FK_Flight_Gate FOREIGN KEY (gate_id) REFERENCES Gate(gate_id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE Flight ADD CONSTRAINT FK_Flight_Airline FOREIGN KEY (airline_id) REFERENCES Airline(airline_id) ON DELETE NO ACTION ON UPDATE CASCADE;